# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92a2236c83bf75ef3e3aad9c4be7fe24d3feb591e033a9ae19108f144f11c04eb19be369f823b0ecb63dba93e6dc885dad53ffb7d8002eea390baf3f1caf63cb

test:
  secret_key_base: d2b6e35ab1d11280b7c00b169fc820b03e43fd4686af7cea802c7aa646682492963534d58baaf049965d85f97d0cf8b4ad16deaee02d07e9cb22da944a27b0c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
